# Generated by Django 5.2.17 on 2026-09-14 14:47

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('architecture', 'Architecture'), ('delivery', 'Delivery'), ('quality', 'Quality'), ('security', 'Security'), ('product', 'Product'), ('embedded', 'Embedded')], max_length=30)),
            ],
            options={
                'ordering': ['stable_id'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('stable_id', models.SlugField(help_text='Stable editorial identifier shared by all locale translations.', max_length=100)),
                ('hero_eyebrow', models.CharField(max_length=120)),
                ('hero_description', models.TextField()),
                ('highlights_label', models.CharField(max_length=120)),
                ('closing_title', models.CharField(max_length=255)),
                ('closing_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('demonstrated', 'Demonstrated'), ('declared', 'Declared'), ('planned', 'Planned')], max_length=20)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('stable_id', models.SlugField(help_text='Stable editorial identifier shared by all locale translations.', max_length=100)),
                ('eyebrow', models.CharField(max_length=120)),
                ('detail_eyebrow', models.CharField(max_length=120)),
                ('cta_label', models.CharField(max_length=160)),
                ('question', models.TextField()),
                ('supporting_text', models.TextField()),
                ('what_i_worked_on', models.TextField()),
                ('future_improvement', models.TextField()),
                ('origin_description', models.TextField(blank=True)),
                ('narrative', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('origin', models.CharField(choices=[('personal-long-term', 'Personal long-term'), ('its-training', 'ITS training')], max_length=30)),
                ('visual_variant', models.CharField(choices=[('signal-yellow', 'Signal yellow'), ('studio-pink', 'Studio pink'), ('electric-cyan', 'Electric cyan')], max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'stable_id'],
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProfileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('eyebrow', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('paragraphs', models.JSONField(default=list)),
                ('highlights', models.JSONField(default=list)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portfolio.profilepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('cta_label', models.CharField(max_length=160)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_links', to='portfolio.profilepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('provenance', models.CharField(choices=[('repository', 'Repository'), ('project-screenshot', 'Project screenshot'), ('original', 'Original'), ('generated', 'Generated'), ('third-party', 'Third party')], max_length=30)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('decorative', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_assets', to='wagtailimages.image')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='portfolio.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='portfolio.projectclaim')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('evidence_type', models.CharField(choices=[('repository', 'Repository'), ('pull-request', 'Pull request'), ('documentation', 'Documentation'), ('test', 'Test'), ('demo', 'Demo'), ('screenshot', 'Screenshot'), ('report', 'Report')], max_length=30)),
                ('url', models.URLField(blank=True)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('link_label', models.CharField(blank=True, max_length=160)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='portfolio.projectasset')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='portfolio.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectclaim',
            name='evidence',
            field=models.ManyToManyField(related_name='claims', through='portfolio.ClaimEvidence', to='portfolio.projectevidence'),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_links', to='portfolio.projectevidence'),
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('stable_id', models.SlugField(max_length=100)),
                ('kind', models.CharField(choices=[('repository', 'Repository'), ('live-demo', 'Live demo'), ('documentation', 'Documentation'), ('jira', 'Jira'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=160)),
                ('accessibility_label', models.CharField(blank=True, max_length=160)),
                ('url', models.URLField()),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.projectpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projectclaim',
            name='project',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='portfolio.projectpage'),
        ),
        migrations.CreateModel(
            name='ProjectCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.capability')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='portfolio.projectpage')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.capability')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.locale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capability', 'locale'), name='unique_capability_translation_locale')],
            },
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.UniqueConstraint(fields=('claim', 'evidence'), name='unique_claim_evidence'),
        ),
        migrations.AddConstraint(
            model_name='projectcapability',
            constraint=models.UniqueConstraint(fields=('project', 'capability'), name='unique_project_capability'),
        ),
    ]
